"""add enum sifat kriteria and unique constraint penilaian

Revision ID: 3e975ac2396d
Revises: d46f773625e0
Create Date: 2026-01-02 16:56:31.323893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e975ac2396d'
down_revision = 'd46f773625e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kriteria', schema=None) as batch_op:
        batch_op.alter_column('sifat',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Enum('benefit', 'cost', name='sifat_kriteria'),
               existing_nullable=False)

    with op.batch_alter_table('penilaian', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_penilaian_alt_krit', ['alternatif_id', 'kriteria_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penilaian', schema=None) as batch_op:
        batch_op.drop_constraint('uq_penilaian_alt_krit', type_='unique')

    with op.batch_alter_table('kriteria', schema=None) as batch_op:
        batch_op.alter_column('sifat',
               existing_type=sa.Enum('benefit', 'cost', name='sifat_kriteria'),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
