"""ubah penilaian dan hasil rekomendasi

Revision ID: 7ec2bac963c7
Revises: ea7edb939f4d
Create Date: 2026-01-03 01:55:23.730356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec2bac963c7'
down_revision = 'ea7edb939f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hasil_rekomendasi', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('hasil_rekomendasi_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'alternatif', ['alternatif_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hasil_rekomendasi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('hasil_rekomendasi_ibfk_1'), 'alternatif', ['alternatif_id'], ['id'])

    # ### end Alembic commands ###
