"""tambah kolom gambar alternatif

Revision ID: 8d3ae22a5858
Revises: 7ec2bac963c7
Create Date: 2026-01-03 01:59:28.771690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d3ae22a5858'
down_revision = '7ec2bac963c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alternatif', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gambar', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alternatif', schema=None) as batch_op:
        batch_op.drop_column('gambar')

    # ### end Alembic commands ###
