"""initial

Revision ID: ab231ca08311
Revises: 
Create Date: 2025-12-30 11:14:33.259768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab231ca08311'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alternatif',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.String(length=5), nullable=False),
    sa.Column('nama_motor', sa.String(length=100), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode')
    )
    op.create_table('kriteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.String(length=5), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('sifat', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('hasil_rekomendasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alternatif_id', sa.Integer(), nullable=False),
    sa.Column('skor_saw', sa.Float(), nullable=True),
    sa.Column('skor_topsis', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alternatif_id'], ['alternatif.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('penilaian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alternatif_id', sa.Integer(), nullable=False),
    sa.Column('kriteria_id', sa.Integer(), nullable=False),
    sa.Column('nilai_skor', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['alternatif_id'], ['alternatif.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kriteria_id'], ['kriteria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('penilaian')
    op.drop_table('hasil_rekomendasi')
    op.drop_table('users')
    op.drop_table('kriteria')
    op.drop_table('alternatif')
    # ### end Alembic commands ###
