"""tambah kolom bobot di tabel kriteria

Revision ID: d46f773625e0
Revises: ab231ca08311
Create Date: 2026-01-02 16:28:22.405071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd46f773625e0'
down_revision = 'ab231ca08311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kriteria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bobot', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kriteria', schema=None) as batch_op:
        batch_op.drop_column('bobot')

    # ### end Alembic commands ###
