"""Update struktur tabel kriteria dan penilaian

Revision ID: ea7edb939f4d
Revises: 99e731ae32c1
Create Date: 2026-01-03 00:55:09.310988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea7edb939f4d'
down_revision = '99e731ae32c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_kriteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kriteria_id', sa.Integer(), nullable=False),
    sa.Column('nama_sub', sa.String(length=100), nullable=False),
    sa.Column('nilai', sa.Float(), nullable=False),
    sa.Column('keterangan', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['kriteria_id'], ['kriteria.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('penilaian', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_kriteria_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('penilaian_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'kriteria', ['kriteria_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'sub_kriteria', ['sub_kriteria_id'], ['id'])
        batch_op.drop_column('nilai_skor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penilaian', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nilai_skor', mysql.FLOAT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('penilaian_ibfk_2'), 'kriteria', ['kriteria_id'], ['id'])
        batch_op.drop_column('sub_kriteria_id')

    op.drop_table('sub_kriteria')
    # ### end Alembic commands ###
